language: java

addons:
  sonarcloud:
    organization: "inseefr"

sudo: required

env:
  - ORBEON_URL_CE=https://github.com/orbeon/orbeon-forms/releases/download/tag-release-2017.1-ce/orbeon-2017.1.201706222342-CE.zip
  - ORBEON_URL_PE=https://github.com/orbeon/orbeon-forms/releases/download/tag-release-2017.1.1-ce/orbeon-2017.1.1.201709122316-PE.zip

script:
  - ./script/getCleanedOrbeon.sh $ORBEON_URL_CE
  - mvn clean install
  - docker build -t laurentc35/stromae .

deploy:
  - skip_cleanup: true
    provider: script
    script:
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      && docker push laurentc35/stromae
